#!/usr/bin/bash
#
# Copyright (C) 2026 Yağız Zengin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

echo ".githooks/pre-commit triggered. Reformatting code!!!"

output=$(build/scripts/reformat.sh --working-directory=$PWD)
if [ -z "$output" ]; then
    echo "Nothing to reformat."
else
    while IFS= read -r f; do
        echo "Adding formatted source file to git: $f"
        git add "$f"
    done <<< "$output"
fi

echo "Reformat complete."
