/*
 * Copyright (C) 2026 Yağız Zengin
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * @file CleanLogPlugin.cpp
 * @author Yağız Zengin ([YZBruh](https://github.com/YZBruh))
 * @brief Implementation of the CleanLogPlugin for clearing PMT logs.
 *
 * This file implements the CleanLogPlugin class which provides functionality
 * to clear the log files generated by the Partition Manager Tool.
 */

#include <PartitionManager/PartitionManager.hpp>
#include <PartitionManager/Plugin.hpp>

#define PLUGIN "CleanLogPlugin"
#define PLUGIN_VERSION "1.2"

namespace PartitionManager {

/**
 * @brief Plugin for clearing PMT log files.
 *
 * This plugin provides functionality to clear the log files
 * generated by the Partition Manager Tool.
 */
class CleanLogPlugin final : public BasicPlugin {
public:
  Helper::CMDLine::Subcommand *cmd = nullptr;
  BasicFlags *flags = nullptr;

  /// @brief Default constructor.
  PLUGIN_SECTION CleanLogPlugin() = default;
  /// @brief Default destructor.
  PLUGIN_SECTION ~CleanLogPlugin() override = default;

  /**
   * @brief Load the plugin and register its subcommand.
   *
   * @param mainApp The main application instance.
   * @param mainFlags The global flags structure.
   * @return true if the plugin loaded successfully.
   */
  PLUGIN_SECTION bool onLoad(Helper::CMDLine::App &mainApp, BasicFlags &mainFlags) override {
    Log::info("{}::onLoad() trigger. Initializing...", PLUGIN);
    cmd = mainApp.addSubcommand("clean-logs", "Clean PMT logs.");
    cmd->addFlag("-v,--version", nullptr, "View version of plugin.")
        ->superior()
        ->callback(Helper::CMDLine::Callbacks::ViewPluginVersion(PLUGIN, PLUGIN_VERSION));
    flags = &mainFlags;
    return true;
  }

  /// @brief Unload the plugin and clean up resources.
  PLUGIN_SECTION bool onUnload() override {
    Log::info("{}::onUnload() trigger. Bye!", PLUGIN);
    cmd = nullptr;
    return true;
  }

  /// @brief Check if the plugin's subcommand was used.
  PLUGIN_SECTION bool used() override { return cmd->isUsed(); }

  /**
   * @brief Run the log cleaning operation.
   *
   * @return true if the log file was successfully removed.
   */
  PLUGIN_SECTION bool run() override {
    Log::info("Removing log file: {}", Flags.logFile);
    Helper::Logger::Properties::setLogging(true); // eraseEntry writes log!
    return Helper::eraseEntry(Flags.logFile);
  }

  /// @brief Get the plugin name.
  PLUGIN_SECTION std::string getName() override { return PLUGIN; }

  /// @brief Get the plugin version.
  PLUGIN_SECTION std::string getVersion() override { return PLUGIN_VERSION; }
};

} // namespace PartitionManager

REGISTER_PLUGIN(PartitionManager, CleanLogPlugin)
