#
# Copyright (C) 2026 Yağız Zengin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

name: Build and Deploy Doxygen Docs

on:
  workflow_dispatch:
    inputs:
      DOCS_PATH:
        description: 'Path for uploading doxygen artifacts.'
        required: true
        default: '/var/www/documentations/pmt-renovated-git'
      USE_GIT_CID:
        description: 'Use git commit ID as project number'
        required: true
        default: 'true'
        type: boolean
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'docs/**'
      - 'srclib/**'
      - 'include/**'
      - 'Doxyfile'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: epyc-runner
    env:
      DOCS_PATH: ${{ github.event.inputs.DOCS_PATH || '/var/www/documentations/pmt-renovated-git' }}
      USE_GIT_CID: ${{ github.event.inputs.USE_GIT_CID || 'true' }}
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          clean: true

      - name: Setup Packages
        run: sudo apt update && sudo apt install git doxygen graphviz -y

      - name: Run Doxygen
        run: |
          if $USE_GIT_CID; then
            SHORT_SHA=$(git rev-parse --short HEAD)
            if ! [ $? -eq 0 ]; then
              echo "::error::git rev-parse fail."
              exit 1
            else
              echo "Resolved SHORT_SHA: $SHORT_SHA"
            fi
            sed -i "s/^PROJECT_NUMBER *=.*/PROJECT_NUMBER         = git-${SHORT_SHA}/" Doxyfile
          fi
          doxygen Doxyfile

      - name: Deploy
        run: |
          rsync -avz --delete docs/html/ $DOCS_PATH

      - name: Clean up workspace
        if: always()
        run: |
          bash build/scripts/build.sh cleanup-generated-docs
